version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6-jdk-12
    steps:
      - checkout
      - run:
          name: Build
          command: 'mvn clean install'
workflows:
  version: 2
  master_workflow:
    jobs:
      - build